### ISSUE TITLE
Blog todos

### ISSUE THREAD

**Issue by AyushExel** [lancedb/lancedb#1063]
### Description

Aesthetics, formatting and styles to-do list for [blog.lancedb.com](https://blog.lancedb.com/)

### Todos

- [x] Fix image background color issue in dark mode via CSS (like for [this post](https://blog.lancedb.com/substrait-powered-filter-pushdown-in-lance-3d204355365c/))
- [ ] Callout boxes/block quotes should have the same color as main text (no bold, but with italics) - sample post: [this one](https://blog.lancedb.com/lancedb-polars-2d5eb32a8aa3/)
- [ ] Author names appear capitalized at the bottom of each post - they should be title case
- [ ] Update tags in blog post to make them more meaningful and allow users to filter based on keywords of interest (up to 3-4 tags per post makes sense). For example, in the RAG posts, `rag` and other relevant keywords, such as `hybrid-search`, could be tags.
- [ ] Every blog post should start with a subtitle that compliments the main title. Some posts (like [this one](https://blog.lancedb.com/substrait-powered-filter-pushdown-in-lance-3d204355365c/)) contain manually specified author names on top, which is inconsistent with the rest of the posts
  - [ ] In [this post](https://blog.lancedb.com/benchmarking-lancedb-92b01032874a-2/) the title could be broken down into a main title and subtitle rather than just starting off the blog directly
- [ ] Code fonts are still relatively ugly compared to the rest of the text (the transition from reading a paragraph of text to reading code is rather jarring) - a custom code font like IBM Plex Mono or similar would look much better on modern browsers.
- [x] Change Ghost blog title to "LanceDB Blog" - it's currently showing on Google search as "LanceDB Company Blog" - the word "company" is redundant for this purpose.
