### ISSUE TITLE
Feature: Simple remote server implementation

### ISSUE THREAD

**Issue by westonpace** [lancedb/lancedb#1118]
### SDK

Rust

### Description

An HTTP remote client has existed as part of LanceDb for a while.  However, there is no corresponding HTTP server.  We should develop a basic HTTP server that users can use if they need some kind of client/server model.  Potential use cases:

 * A user wants to query lancedb from systems outside of their datacenter (e.g. they are using S3 and they want to query outside of EC2)
 * A user wants to create an ad-hoc API for some language that isn't yet supported (e.g. perl :smile: )

## Tasks

 - [ ] Investigate and choose a technology for HTTP rust servers (actix / tower / etc.)
 - [ ] Create basic http server implementation in Rust
 - [ ] Implement remote table implementation
 - [ ] Wire up http scheme in connect to automatically use the remote client
 - [ ] End-to-end integration testing
