### ISSUE TITLE
OSS/Cloud Integrations Epic

### ISSUE THREAD

**Issue by AyushExel** [lancedb/lancedb#1233]
### Week of 17th
- [x] Embedchain OSS integration 
### Week of 10th june:
- [x] Langchain integrations updates - [hybrid search, audio, image ingestion support]
- [ ] R2R waiting on author

### Description

patch updates:
- [x] Llama-index [General improvements and hybrid search]  :  TODO
- [x] Langchain [hybrid search]
- [x] Langroid : WIP
- [x] Langchain [ General Updates]

TODO OSS Cloud Integrations:
- [x] R2R
- [x] Llama-index
- [x] Langchain
- [x] Langroid

Integration Docs/Examples:
- [x] langchain
- [x] LLama-index

### Link

https://github.com/lancedb/lancedb-internal/issues/48
https://github.com/lancedb/lancedb-internal/issues/50
