### ISSUE TITLE
Docs Epic

### ISSUE THREAD

**Issue by AyushExel** [lancedb/lancedb#1476]
### Description

This epic will primarily deal with how we want to organise the docs content, its layout, structure and presentation so that user experience is standardised across sub-sections.

### Examples ([URL](https://lancedb.github.io/lancedb/examples/))
- [x] Port curated examples from recipes repo and with verbose explainations.
- [x] Add node example and applications

### Integrations ([URL](https://lancedb.github.io/lancedb/integrations/))
- [x] Llama-index ts integration page
- [x] #1589
- [x] #1588
- [x] #1587
- [x] Langchain

### Managing embeddings ([URL](https://lancedb.github.io/lancedb/embeddings/))
- [x] Each embedding function should have its own dedicated page similar to rerankers
- [x] #1584

### Rerankers
- [x] #1585
- [x] #1586

### Benchmarks (Missing)
- [ ] Show LanceDB's performance( ingestion, query, random access, filters) across various settings (local, cloud) using various sources( local, gcp, aws etc.)

### Studies (Missing)
- [x] Show detailed ablation studies on the effect of tuneable parameters on various performance metrics
- [ ]

**Comment by AyushExel** [comment]
## Missing features
- [ ] Multi-vector support

## Structural
- [ ] Agent friendly docs

**Comment by AyushExel** [comment]
https://github.com/lancedb/lancedb/issues/2195

**Comment by AyushExel** [comment]
https://github.com/lancedb/lancedb/issues/2328

**Comment by evolari** [comment]
[Discord feedback 
](https://discord.com/channels/1030247538198061086/1030247538667827251/1362440616302219375)
A user (jd) flagged that the docs could be much clearer, it took them a full day to figure out how LanceDB works with PyTorch, including integration with Torch Dataloader and HuggingFace datasets.

They also struggled to understand how LanceDB behaves in distributed training setups and how to handle fault tolerance in such environments.

**Comment by evolari** [comment]
from community feedback chat
Docs not in great shape.  Hard to navigate.  Feels like I’m on different websites.  Missing docs on integrations with dataframe libraries.

**Comment by AyushExel** [comment]
we're not updating the old docs anymore. All new development will happen on documentation/ repo
