### ISSUE TITLE
[Epic] Hybrid search & Reranking features & enhancements

### ISSUE THREAD

**Issue by AyushExel** [lancedb/lancedb#1676]
### SDK

Python

### Description

Bug fixes / Enhancements:
- [x] Depricate/Remove `return_score` support from rerankers & enforce all rerankers should return only "_relevance_score". return_score support was initially meant for debugging purposes, but ended up staying on as a feature. Fixes https://github.com/lancedb/lancedb/issues/1675
- [x] Remove "normalize" option for hybrid search
- [ ] ~ Fill values FTS or Vector result list has a missing row. Currently missing score is NaN https://github.com/lancedb/lancedb/issues/1671 ~ wontfix

SaaS disparity:
-  [x] https://github.com/lancedb/lancedb/issues/1697

Rust Support:

Node Support:
